CREATE TABLE user_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_type VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE statuses (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE connection_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    connection_type VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE cities (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    city_name VARCHAR(50) NOT NULL UNIQUE
);

CREATE TABLE issue_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_level INT NOT NULL,
    parent_issue INT REFERENCES issue_types(id),
    name VARCHAR(100) NOT NULL,
    insert_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    email VARCHAR(100),
    login VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    telephone VARCHAR(50),
    id_user_type INTEGER NOT NULL REFERENCES user_types(id)
);

CREATE TABLE pos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    telephone VARCHAR(50),
    cellphone VARCHAR(50),
    address VARCHAR(255) NOT NULL,
    id_city INTEGER NOT NULL REFERENCES cities(id),
    model VARCHAR(100) NOT NULL,
    brand VARCHAR(100) NOT NULL,
    id_conn_type INTEGER NOT NULL REFERENCES connection_types(id),
    morning_opening TIME,
    morning_closing TIME,
    afternoon_opening TIME,
    afternoon_closing TIME,
    days_closed VARCHAR(20),
    insert_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE issues (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_pos BIGINT NOT NULL REFERENCES pos(id),
    id_type INTEGER NOT NULL REFERENCES issue_types(id),
    id_sub_type INTEGER NOT NULL REFERENCES issue_types(id),
    problem VARCHAR(255),
    priority VARCHAR(20) NOT NULL DEFAULT 'NORMAL',
    id_status INTEGER NOT NULL REFERENCES statuses(id),
    memo VARCHAR(255),
    id_user_created BIGINT REFERENCES users(id),
    id_assigned BIGINT REFERENCES user_types(id),
    description TEXT,
    assigned_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    creation_date TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modif_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    solution TEXT
);

CREATE TABLE logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    issue_id BIGINT NOT NULL REFERENCES issues(id) ON DELETE CASCADE,
    date_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    action VARCHAR(50) NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id),
    notes TEXT
);